command:
  - uvicorn
  - main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: CATALOG
    value: "${var.catalog}"
  - name: SCHEMA
    value: gold
  - name: MODEL_ENDPOINT
    value: "${var.model_endpoint_name}"
  - name: SQL_WAREHOUSE_ID
    value: "${var.warehouse_id}"
  - name: GOOGLE_MAPS_API_KEY
    value: "${var.google_maps_api_key}"
