command:
  - uvicorn
  - main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: CATALOG
    value: "serverless_stable_h7wanf_catalog"
  - name: SCHEMA
    value: gold
  - name: MODEL_ENDPOINT
    value: "qsr-site-scoring"
  - name: SQL_WAREHOUSE_ID
    value: "4047b28d66a51bdc"
  - name: GOOGLE_MAPS_API_KEY
    value: ""
